version: '2'

services:
  db:
    image: mdillon/postgis:9.4
    environment:
      # POSTGRES_DB: welltory_test
      POSTGRES_DB: postgres
  web:
    build: .
    command: ./wait-for-postgres.sh db python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # DJANGO_DB_NAME: welltory_test
      DJANGO_DB_NAME: postgres
      DJANGO_DB_HOST: db
