# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 17:18
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(verbose_name='Время начала')),
                ('time_end', models.DateTimeField(verbose_name='Время конца')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Гео-точка')),
            ],
            options={
                'verbose_name_plural': 'Гео-данные',
                'verbose_name': 'Гео-данные',
            },
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(verbose_name='Время начала')),
                ('time_end', models.DateTimeField(verbose_name='Время конца')),
            ],
            options={
                'verbose_name_plural': 'Сны',
                'verbose_name': 'Сон',
            },
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(verbose_name='Время начала')),
                ('time_end', models.DateTimeField(verbose_name='Время конца')),
                ('count', models.PositiveIntegerField(verbose_name='Количество шагов')),
            ],
            options={
                'verbose_name_plural': 'Шаги',
                'verbose_name': 'Шаги',
            },
        ),
    ]
